### ISSUE TITLE
SIP trinket provider

### ISSUE THREAD

**Issue by virus2016** [davehorton/drachtio#13]
*Wow autocorrect - SIP Trunk provider*

Hi there, 

Just wondering if I am able to register with another sip server/provider and handle the flow?

Many thanks,

**Comment by davehorton** [comment]
Yes, you could do this.

By the way, this project has been subsumed into drachtio-srf (https://github.com/davehorton/drachtio-srf), so if you need help showing exactly how to do this please open an issue there
